sudo: required

services:
  - docker

script:
  - | 
    docker build -t res0nance/flutter . \
    --build-arg ANDROID_SDK_TOOLS="3859397" \
    --build-arg ANDROID_BUILD_TOOLS="27.0.3" \
    --build-arg ANDROID_COMPILE_SDK=24 \
    --build-arg FLUTTER_VERSION="0.3.1-beta"
  - docker ps -a
